%%%
  VERSION:1
  LANGUAGE:ENGLISH
%%%
MODULE MOD_codo

    ! -------------------------------
    ! Define customized variables here
    ! ...

	! Tool variables: 
	PERS tooldata RobotiQ2F85Gripper(FullyClosed) := [TRUE,[[0.000,0.000,130.000],[1.00000000,0.00000000,0.00000000,0.00000000]],[1,[0,0,20],[1,0,0,0],0,0,0.005]];

	! Reference variables:
	PERS wobjdata Frame2 := [FALSE, TRUE, "", [[0,0,0],[1,0,0,0]],[[-140.437,-738.971,5.234],[1.00000000,0.00000000,0.00000000,0.00000000]]];

	PROC Main()
		ConfJ \On;
		ConfL \Off;
		! Program generated by RoboDK v5.9.2 for ABB IRB 140-6/0.8 on 24/07/2025 22:47:51
		! Using nominal kinematics.
		MoveAbsJ [[0.000000,0.000000,0.000000,0.000000,0.000000,-0.000000],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]],v500,z1,RobotiQ2F85Gripper(FullyClosed) \WObj:=Frame2;
		MoveAbsJ [[-73.180000,0.000000,0.000000,0.000000,0.000000,-0.000000],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]],v500,z1,RobotiQ2F85Gripper(FullyClosed) \WObj:=Frame2;
		MoveAbsJ [[-73.170000,0.000000,-230.000000,0.000000,0.000000,-0.000000],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]],v500,z1,RobotiQ2F85Gripper(FullyClosed) \WObj:=Frame2;
		MoveAbsJ [[-73.170000,0.000000,50.000000,0.000000,0.000000,-0.000000],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]],v500,z1,RobotiQ2F85Gripper(FullyClosed) \WObj:=Frame2;
		MoveAbsJ [[-73.180000,0.000000,0.000000,0.000000,0.000000,-0.000000],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]],v500,z1,RobotiQ2F85Gripper(FullyClosed) \WObj:=Frame2;
		MoveAbsJ [[0.000000,0.000000,0.000000,0.000000,0.000000,-0.000000],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]],v500,z1,RobotiQ2F85Gripper(FullyClosed) \WObj:=Frame2;
	ENDPROC

ENDMODULE
