global _start\n;Robot Control Program - 3 Motors
;Generated by Robot Lexical Analyzer

PORTA   EQU 00H     ; Puerto A - Motor Base  
PORTB   EQU 02H     ; Puerto B - Motor Hombro
PORTC   EQU 04H     ; Puerto C - Motor Codo
Config  EQU 06H     ; Puerto configuracion 8255

section .data


section .text


START:
    ; Inicializar
    MOV   AX, DATA_SEG
    MOV   DS, AX
    
    ; Configurar 8255 - todos puertos como salida
    MOV   DX, Config
    MOV   AL, 80H
    OUT   DX, AL
    
    ; Motor A (Base) - Secuencia de pasos
    MOV   DX, PORTA
    MOV   AL, 06H      ; Paso 1
    OUT   DX, AL
    CALL  DELAY
    MOV   AL, 0CH      ; Paso 2  
    OUT   DX, AL
    CALL  DELAY
    MOV   AL, 09H      ; Paso 3
    OUT   DX, AL
    CALL  DELAY
    MOV   AL, 03H      ; Paso 4
    OUT   DX, AL
    CALL  DELAY
    
    ; Motor B (Hombro) - Secuencia de pasos
    MOV   DX, PORTB
    MOV   AL, 06H      ; Paso 1
    OUT   DX, AL
    CALL  DELAY
    MOV   AL, 0CH      ; Paso 2
    OUT   DX, AL
    CALL  DELAY
    MOV   AL, 09H      ; Paso 3
    OUT   DX, AL
    CALL  DELAY
    MOV   AL, 03H      ; Paso 4
    OUT   DX, AL
    CALL  DELAY
    
    ; Motor C (Codo) - Secuencia de pasos
    MOV   DX, PORTC
    MOV   AL, 06H      ; Paso 1
    OUT   DX, AL
    CALL  DELAY
    MOV   AL, 0CH      ; Paso 2
    OUT   DX, AL
    CALL  DELAY
    MOV   AL, 09H      ; Paso 3
    OUT   DX, AL
    CALL  DELAY
    MOV   AL, 03H      ; Paso 4
    OUT   DX, AL
    CALL  DELAY
    
    ; Terminar programa
    MOV    AH,4CH
    MOV    AL,0
    INT    21H

DELAY:
    ; Delay loop para control de velocidad
    PUSH  CX
    MOV   CX, 0FFFFH
DELAY_LOOP:
    LOOP  DELAY_LOOP
    POP   CX
    RET



